//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenInvoicePeru.WinApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=jck.hostbsd.com;database=FacturasElectronicasBruno;User ID=sa;Password=Aa1" +
            "2345*")]
        public string CadenaConexionBruno {
            get {
                return ((string)(this["CadenaConexionBruno"]));
            }
            set {
                this["CadenaConexionBruno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=190.119.219.134;database=PacasmayoFE;User ID=Diresa;Password=12345")]
        public string CadenaConexionGuadalupe {
            get {
                return ((string)(this["CadenaConexionGuadalupe"]));
            }
            set {
                this["CadenaConexionGuadalupe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=jck.hostbsd.com;database=FacturasElectronicasWeb;User ID=sa;Password=Aa123" +
            "45*")]
        public string CadenaConexionWeb {
            get {
                return ((string)(this["CadenaConexionWeb"]));
            }
            set {
                this["CadenaConexionWeb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=(local);database=FacturasElectronicasRodiscar;User ID=sa;Password=12345")]
        public string CadenaConexionLocal {
            get {
                return ((string)(this["CadenaConexionLocal"]));
            }
            set {
                this["CadenaConexionLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=campos.hostbsd.com;database=colegio;User ID=sa;Password=Aa12345*")]
        public string CadenaConexionColegio {
            get {
                return ((string)(this["CadenaConexionColegio"]));
            }
            set {
                this["CadenaConexionColegio"] = value;
            }
        }
    }
}
